name: 'Choreo BYOG Branch Create'
description: 'Create a new BYOG trigger'
author: WSO2
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
runs:
  using: node16
  main: index.js
inputs:
  token:
    required: true
    description: 'The token of the user repository'
  org:
    required: true
    description: 'The organization name of the user repository'
  userRepoName:
    required: true
    description: 'The name of the user repository'
  branch:
    required: true
    description: 'The branch of the user repository which going to push changes'
  headBranch:
    required: false
    description: 'The head branch of the user repository'
    default: 'main'
  gitProvider:
    required: false
    description: 'The git provider of the user repository'
    default: 'github'
  username:
    required: false
    description: 'The username of the user repository'